name: Adify-CI

on: [push]

jobs:
  running_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Installing dependencies
        run: pip3 install -r requirements.txt
      - name: Running tests
        run: python3 manage.py test
