name: Adify-CI

on: [push]

jobs:
  running_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Installing dependencies
        run: pip3 install -r requirements.txt
      - name: Setupping DB
        run: python3 manage.py makemigrations && python3 manage.py migrate
      - name: Running tests
        run: python3 manage.py test --parallel 4
